version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./gradlew build

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: /gradlew test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: main