--create table users
--(id bigint generated by default as identity,
-- email varchar(255) not null,
-- password varchar(500) not null,
-- primary key (id))

CREATE TABLE users (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(500) NOT NULL
);
