--create table addresses
--(id bigint generated by default as identity,
-- line_no_one varchar(3000) not null,
-- line_no_two varchar(3000) not null,
-- city varchar(500) not null,
-- state varchar(500) not null,
-- pin_code varchar(100) not null,
-- country varchar(100) not null,
-- is_default boolean,
-- user_id bigint,
-- primary key (id),
-- CONSTRAINT fk_user_addresses FOREIGN KEY(user_id) references users(id))

CREATE TABLE addresses (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    line_no_one VARCHAR(3000) NOT NULL,
    line_no_two VARCHAR(3000) NOT NULL,
    city VARCHAR(500) NOT NULL,
    state VARCHAR(500) NOT NULL,
    pin_code VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    is_default BIT,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_user_addresses FOREIGN KEY (user_id) REFERENCES users(id)
);

