--CREATE TABLE orders (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--    book_id BIGINT NOT NULL,
--    user_id BIGINT NOT NULL,
--    shipping_address_id BIGINT NOT NULL,
--    payment_method PAYMENT_METHOD_ENUM,
--    shipping_cost DOUBLE PRECISION,
--    total_cost DOUBLE PRECISION,
--    currency VARCHAR(10),
--    item_count INT,
--    PRIMARY KEY (id),
--    FOREIGN KEY (book_id) REFERENCES books(id),
--    FOREIGN KEY (user_id) REFERENCES users(id),
--    FOREIGN KEY (shipping_address_id) REFERENCES addresses(id)
--);

CREATE TABLE orders (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shipping_address_id BIGINT NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    shipping_cost FLOAT,
    total_cost FLOAT,
    currency VARCHAR(10),
    item_count INT,
    CONSTRAINT fk_books_orders FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT fk_users_orders FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_addresses_orders FOREIGN KEY (shipping_address_id) REFERENCES addresses(id)
);
