CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shipping_address_id BIGINT NOT NULL,
    payment_method PAYMENT_METHOD_ENUM,
    shipping_cost DOUBLE PRECISION,
    total_cost DOUBLE PRECISION,
    currency VARCHAR(10),
    item_count INT,
    PRIMARY KEY (id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (shipping_address_id) REFERENCES addresses(id)
);